# env/environment.yml
name: insurefit
channels: [conda-forge]
dependencies:
  - r-base=4.4
  - compilers
  - make
  - pkg-config
  - git
  - libblas=*=*openblas
  - r-rcpp
  - r-rcpparmadillo
  - r-devtools
  - r-here
  - r-usethis
  - r-testthat
  - r-microbenchmark # r-bench not on conda forge
  - r-shiny
  - r-ggplot2